# Site settings
title: OpenMessaging
email: yukon@apache.org
description: > # this means to ignore newlines until "baseurl:"
  OpenMessaging is cloud-oriented and vendor-neutral, provides industry guidelines for areas of finance, e-commerce, IoT and big-data, and aimed to develop messaging and streaming applications across heterogeneous systems and platforms.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

paginate: 4
paginate_path: "blog/page:num"

plugins:
- jekyll-paginate

include:
- _internal

defaults:
- scope:
    path: docs
  values:
    layout: docs